server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 在此处配置需要绑定的rabbitMQ的信息
        defaultRabbit: # 消息服务设置的名称，用于bindings整合
          type: rabbit # 消息组件类型
          environment: # rabbitmq环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        output: # 通道名
          destination: test-stream # rabbitmq的exchange的名称
          content-type: application/json
          binder: defaultRabbit # 消息服务设置的名称
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka