server:
  port: 8506
spring:
  application:
    name: microservicecloud-consul-consumer
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: false  #注册到consul的服务名称