server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul:
  #ignored-services: microservicecloud-dept
  prefix: /atguigu      #设置统一公共前缀 http://myzuul.com:9527/atguigu/mydept/dept/get/2
  ignored-services: "*"  #单个具体，多个可以用"*"  禁用原来的服务名称访问，仅可用代理名称访问 microservicecloud-dept 不可访问 应使用/mydept/**  http://myzuul.com:9527/mydept/dept/get/2
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

