server:
  port: 8503
spring:
  application:
    name: microservicecloud-consul-producer
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: service-producer #注册到consul的服务名称
        healthCheckPath: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
management:
  endpoint:
    health:
      show-details: always  #显示健康具体信息，默认不会显示详细信息
  endpoints:
    web:
      exposure:
        include: '*'    # 暴露所有节点