server:
  port: 8503
spring:
  application:
    name: microservicecloud-consul-producer
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: service-producer #注册到consul的服务名称