server:
  port: 2201

spring:
  application:
    name: seata-order-service
#  cloud:
##    alibaba:
##      seata:
##        tx-service-group: fsp_tx_group
#    nacos:
#      discovery:
#        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
seata:
  enabled: true
  application-id: ${spring.application.name}-seata
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: localhost:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      namespace:
      userName: "nacos"
      password: "nacos"

feign:
  hystrix:
    enabled: false

  logging:
    level:
      io:
        seata: info